Repository 1024pix/pix-bot, pull requests merged in 2020-10, with the labels that each got.

#35 [BUGFIX] Correction du nom de l'application PIX LCMS.
  lib/services/slack/commands.js
Labels: Tech Review Needed

#36 [TECH] Ajout de vérification CI avant MER/MEP
  lib/controllers/slack.js
  lib/services/github.js
  lib/services/slack/surfaces/messages/.gitkeep
  lib/services/slack/surfaces/messages/post-message.js
  lib/services/slack/view-submissions.js
  test/unit/services/github_test.js
Labels: cross-team

#38 [FEATURE] Display Pull-request labels on slack message
  lib/services/github.js
  test/unit/services/github_test.js
Labels: cross-team, ready for review

#34 [FEATURE] Deployer pix-site et pix-pro désormais dans le même repo (PIX-1266)
  lib/controllers/slack.js
  lib/routes/slack.js
  lib/services/releases.js
  lib/services/slack/commands.js
  test/unit/services/releases_test.js
  test/unit/services/slack/commands_test.js
Labels: team-evaluation, team-prescription

#40 [TECH] Création de la release de `pix-app` sur Sentry.
  scripts/publish.sh
Labels: cross-team

#41 [FEATURE] Remonter le quota d'utilisation de SendInBlue.
  bin/www
  lib/config.js
  lib/services/cron-job.js
  lib/services/sendinblue-report.js
  package-lock.json
  package.json
  sample.env
  test/unit/services/sendinblue-report_test.js
Labels: cross-team
