Repository 1024pix/pix-bot, pull requests merged in 2020-09, with the labels that each got.

#28 Supprimer le script de déploiement bash obsolète
  README.md
  docs/deploy.puml
  scripts/deploy.sh
Labels: documentation

#29 [TECH] Ajout d'une action Slack pour déployer pix-ui
  lib/controllers/slack.js
  lib/routes/slack.js
  lib/services/releases.js
  lib/services/slack/commands.js
  scripts/common.sh
  scripts/deploy-pix-ui.sh
  scripts/get-pull-requests-to-release-in-prod.js
  scripts/publish.sh
  scripts/release-pix-repo.sh
  test/get-pull-requests-to-release-in-prod_test.js
  test/unit/services/releases_test.js
  test/unit/services/slack/commands_test.js
Labels: cross-team

#30 [FEATURE] Ajout du déploiement de l'API LCMS.
  lib/controllers/slack.js
  lib/routes/slack.js
  lib/server.js
  lib/services/github.js
  lib/services/releases.js
  lib/services/scalingo-client.js
  lib/services/slack/commands.js
  package-lock.json
  package.json
  scripts/get-pull-requests-to-release-in-prod.js
  scripts/release-pix-repo.sh
  test/get-pull-requests-to-release-in-prod_test.js
  test/unit/services/github_test.js
  test/unit/services/releases_test.js
  test/unit/services/scalingo-client_test.js
  test/unit/services/slack/commands_test.js
Labels: Tech Review Needed, cross-team
