Repository 1024pix/pix-bot, pull requests merged in 2022-08, with the labels that each got.

#134 [FEATURE] Créer une commande Slack pour donner les rôles par tour lors d'un mob
  build/controllers/slack.js
  build/manifest.js
  test/acceptance/build/manifest_test.js
Labels: :rocket: Ready to Merge

#135 [FEATURE] Être en capacité d'être notifié en cas d'erreur de deploiement
  build/controllers/scalingo.js
  build/controllers/slack.js
  build/routes/scalingo.js
  common/services/slack/surfaces/messages/post-message.js
  config.js
  test/integration/build/scalingo_test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#137 [BUGFIX] Utiliser les commits entre les 2 releases pour afficher une notification de changement de config lors du déploiement
  common/services/github.js
  run/services/slack/view-submissions.js
  test/acceptance/run/slack_test.js
  test/test-helper.js
  test/unit/build/services/github_test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#139 [BUGFIX] Corrige le déploiement en recette
  package-lock.json
  package.json
  scripts/publish.sh
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#142 [FEATURE] Eviter de déployer une RA si la PR contient le label `no-review-app`.
  build/controllers/github.js
  test/acceptance/build/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
