Repository 1024pix/pix-bot, pull requests merged in 2022-04, with the labels that each got.

#98 [TECH] Monter de version node vers la 16.14
  .nvmrc
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge

#99 Revert "[TECH] Monter de version node vers la 16.14 "
  .nvmrc
  package.json
Labels: cross-team, :rocket: Ready to Merge

#103 [CLEANUP] Supprimer le package npm crypto
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge

#102 [CLEANUP] Supprimer de la duplication sur le webhook Slack
  common/routes/slack.js
  config.js
  test/acceptance/common/slack_test.js
Labels: Tech Review Needed, :rocket: Ready to Merge, team-captains

#107 [CLEANUP] Supprimer l'utilisation de moment.js et nettoyage des dépendances
  common/services/changelog.js
  package.json
Labels: Tech Review Needed, :rocket: Ready to Merge, team-captains

#105 [TECH] Mettre à jour les dépendances
  config.js
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge

#101 [FEATURE] Génére correctement le changelog pour une release après une correction de release à chaud
  common/services/changelog.js
  common/services/github.js
  scripts/common.sh
  scripts/get-pull-requests-to-release-in-prod.js
  test/acceptance/scripts/publish_test.js
  test/unit/common/services/changelog_test.js
Labels: Tech Review Needed, :rocket: Ready to Merge, team-captains

#114 [FEATURE] Générer le manifest pour configurer les applications slack
  README.md
  build/controllers/manifest.js
  build/routes/manifest.js
  run/controllers/manifest.js
  run/routes/manifest.js
  test/acceptance/build/manifest_test.js
  test/acceptance/run/manifest_test.js
Labels: :rocket: Ready to Merge, team-captains

#115 [CLEANUP] Nettoyer les routes du module common
  build/controllers/slack.js
  build/routes/slack.js
  common/controllers/slack.js
  common/routes/slack.js
  run/controllers/manifest.js
  run/controllers/slack.js
  run/routes/slack.js
  test/acceptance/run/manifest_test.js
Labels: :rocket: Ready to Merge, team-captains
