Repository 1024pix/pix-bot, pull requests merged in 2022-09, with the labels that each got.

#145 [TECH] Permettre de linter avec autofix avant chaque commit en local, si besoin.
  .husky/pre-commit
  .lintstagedrc.json
  package-lock.json
  package.json
  server.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#147 [TECH] Linter l'ensemble des fichiers.
  .lintstagedrc.json
  config.js
  package.json
  scripts/get-pull-requests-to-release-in-prod.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#149 [BUGFIX] Le nom du shortcut de création de l'application est trop long.
  run/manifest.js
  test/acceptance/run/manifest_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#150 Mentionner MER/MEP au début du label de l'action de release
  build/manifest.js
  run/manifest.js
  test/acceptance/build/manifest_test.js
  test/acceptance/run/manifest_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#148 [TECH] Mettre à jour cron de 1.8 à 2.1
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#151 [FEATURE] Filtrer les PR draft sur la commande Slack /pr-pix
  common/services/github.js
  test/unit/build/services/github_test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#152 [DX] Construction query string Octokit via function
  common/services/github.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#153 [BUGFIX] Mise à jour de scalingo-review-app-manager
  package-lock.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK
