Repository 1024pix/pix-bot, pull requests merged in 2022-10, with the labels that each got.

#155 [FEATURE] Déployer Gravitee
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
  test/acceptance/run/slashcommand_test.js
  test/integration/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge, team-captains

#156 [TECH] Gérer les erreurs inattendues
  common/pre-response-handler.js
  config.js
  package-lock.json
  package.json
  sample.env
  server.js
  test/acceptance/common/index_test.js
  test/test-helper.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#154 [TECH] Mise à jour des dépendances
  package-lock.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#157 [TECH] Empêcher le merge si un rebase est en cours
  .github/workflows/prevent-fixup-commit.yaml
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK, no-review-app

#158 [BUGFIX] Mise a jour de scalingo-review-app-manager
  package-lock.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#159 [BUGFIX]
  config.js
  test/integration/run/services/slack/commands_test.js
  test/unit/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
