Repository 1024pix/pix-bot, pull requests merged in 2022-06, with the labels that each got.

#130 [FEATURE] Ajouter les review apps pour pix-tutos (PIX-5030)
  build/controllers/github.js
Labels: ready for review, :rocket: Ready to Merge

#126 [CLEANUP] Supprime la config PIX_APPS_TO_DEPLOY
  common/services/releases.js
  config.js
  test/unit/common/services/releases_test.js
Labels: Tech Review Needed, :rocket: Ready to Merge, team-captains

#129 [FEATURE] Déploiement de metabase
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
  test/unit/run/services/slack/commands_test.js
Labels: Tech Review Needed, :rocket: Ready to Merge, team-captains

#131 [TECH] Ajouter une commande de création et de déploiement de Pix Tutos (PIX-5127).
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
  test/unit/run/services/slack/commands_test.js
Labels: team-evaluation, :rocket: Ready to Merge
