Repository 1024pix/pix-bot, pull requests merged in 2022-12, with the labels that each got.

#168 Créer une application Scalingo avec une configuration valide via Slack
  common/models/ScalingoAppName.js
  common/services/scalingo-client.js
  config.js
  run/services/slack/surfaces/modals/scalingo-apps/application-creation-confirmation.js
  run/services/slack/view-submissions.js
  test/acceptance/run/slack_test.js
  test/integration/common/services/slack/view-submissions_test.js
  test/integration/run/services/slack/view-submissions_test.js
  test/test-helper.js
  test/unit/common/services/scalingo-client_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#167 [TECH] Mise à jour de l'environnement
  .circleci/config.yml
  .nvmrc
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#169 [TECH] Mettre à jour environnement (axios, scalingo-cli, octokit/rest)
  .circleci/config.yml
  .nvmrc
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#170 [TECH] Mise à jour de l'environnement
  common/services/scalingo-client.js
  package-lock.json
  package.json
  test/unit/common/services/scalingo-client_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#171 Mettre à jour automatiquement l'environnement
  .github/renovate.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#174 Configure renovate
  .github/renovate.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#179 Signaler clairement les PR renovate
  .github/renovate.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#180 :wrench: Désactiver les limites de PR de renovate
  .github/renovate.json
Labels: cross-team, :rocket: Ready to Merge

#186 [TECH] Créer automatiquement des PR de montées de version
  .github/renovate.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#196 [TECH] Prévenir les incohérences de dépendances
  .depcheckrc
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#197 [TECH] Tracer les appels Github
  common/services/github.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#198 [TECH] Expliciter la description de l'application
  package.json
  test/acceptance/common/index_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#200 [TECH] Linter les tests de manière homogène
  .eslintrc.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#199 [TECH] Tracer les erreurs Github
  common/services/github.js
  common/services/logger.js
  package-lock.json
  package.json
  test/acceptance/run/slack_test.js
  test/test-helper.js
  test/unit/build/services/github_test.js
  test/unit/common/services/logger_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#201 [TECH] Corriger l'orthographe de la notification de déploiement en erreur
  build/controllers/scalingo.js
  common/services/logger.js
  test/acceptance/build/scalingo_test.js
  test/unit/common/services/logger_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#203 [TECH] Supprimer le template de PR en doublon
  docs/pull_request_template.md
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#202 [TECH] Ajouter un lien vers la review-app dans la pull-request
  .editorconfig
  .slugignore
  build/controllers/github.js
  build/templates/pull-request-messages/default.md
  build/templates/pull-request-messages/pix-db-replication.md
  build/templates/pull-request-messages/pix-editor.md
  build/templates/pull-request-messages/pix-site.md
  build/templates/pull-request-messages/pix.md
  common/services/github.js
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
  test/unit/build/controllers/pull-request-messages/pix-bot.md
  test/unit/build/controllers/pull-request-messages/pix-db-replication.md
  test/unit/build/controllers/pull-request-messages/pix-editor.md
  test/unit/build/controllers/pull-request-messages/pix-site.md
  test/unit/build/controllers/pull-request-messages/pix.md
  test/unit/build/services/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#204 [BUGFIX] Les commentaires de PR non sont pas tout à fait corrects
  build/controllers/github.js
  build/templates/pull-request-messages/default.md
  build/templates/pull-request-messages/pix-db-replication.md
  build/templates/pull-request-messages/pix-site.md
  build/templates/pull-request-messages/pix.md
  test/unit/build/controllers/pull-request-messages/pix-bot.md
  test/unit/build/controllers/pull-request-messages/pix-db-replication.md
  test/unit/build/controllers/pull-request-messages/pix-editor.md
  test/unit/build/controllers/pull-request-messages/pix-site.md
  test/unit/build/controllers/pull-request-messages/pix.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#205 [BUGFIX] Les commentaires de PR ne toujours sont pas tout à fait corrects
  build/templates/pull-request-messages/pix-db-replication.md
  build/templates/pull-request-messages/pix-editor.md
  test/unit/build/controllers/pull-request-messages/pix-db-replication.md
  test/unit/build/controllers/pull-request-messages/pix-editor.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#206 [BUGFIX] Les commentaires de PR ne sont toujours pas encore tout à fait corrects
  build/templates/pull-request-messages/pix-editor.md
  test/unit/build/controllers/pull-request-messages/pix-editor.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
