Repository 1024pix/pix-bot, pull requests merged in 2022-11, with the labels that each got.

#161 Adding pix-datawarehouse-data to pix-db-replication app
  config.js
Labels: :rocket: Ready to Merge, team-captains

#162 [BUGFIX] Corrige les crashs liés aux déploiements de Review Apps Scalingo
  build/controllers/github.js
  common/pre-response-handler.js
  test/acceptance/build/github_test.js
  test/acceptance/common/index_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#163 :art: Ecrire les logs d'erreurs sur une ligne
  common/pre-response-handler.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#164 Mise à jour du nom des application Gravitee APIM
  config.js
  test/integration/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#165 [TECH] Déployer Airflow en production depuis Slack
  common/services/scalingo-client.js
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
  test/acceptance/run/slashcommand_test.js
  test/integration/run/services/slack/commands_test.js
  test/unit/common/services/scalingo-client_test.js
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#166 [TECH] Tracer le message d'erreur du CDN
  run/services/cdn.js
  test/integration/run/services/cdn_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
