Repository 1024pix/pix-bot, pull requests merged in 2023-03, with the labels that each got.

#222 Expliciter la configuration de l'ecoMode
  build/services/eco-mode-service.js
  config.js
  sample.env
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#232 [TECH] Mise à jour des dépendances
  package-lock.json
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#231 [TECH] :sparkles: Réessayer l'invalidation de cache en cas d'échec
  config.js
  package-lock.json
  package.json
  run/services/cdn.js
  test/integration/run/services/cdn_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#234 :sparkles: Ajout de l'URL des review-app de scalingo de pix1d sur les messages github
  build/templates/pull-request-messages/pix.md
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#233 [FEATURE] Au push sur une PR, on déploie nous même la review app
  build/controllers/github.js
  common/services/scalingo-client.js
  test/acceptance/build/github_test.js
  test/unit/common/services/scalingo-client_test.js
Labels: enhancement, cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#235 Déployer le code à la création de la RA
  build/controllers/github.js
  test/acceptance/build/github_test.js
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#236 [TECH] Utiliser la version de release qui vient d'être crée plutôt que d'appeler l'API Github
  build/services/slack/view-submissions.js
  common/services/releases.js
  index.js
  run/controllers/deploy-sites.js
  run/services/deploy.js
  run/services/slack/commands.js
  scripts/release-pix-repo.sh
  test/acceptance/scripts/release-pix-repo_test.js
  test/unit/common/services/releases_test.js
  test/unit/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#237 Prendre en compte le status ouvert d'une PR lors d'une synchro / dépoloiement de RA
  build/controllers/github.js
  test/acceptance/build/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#238 Créer des RA en cas de réouverture de PR
  build/controllers/github.js
  test/acceptance/build/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
