Repository 1024pix/pix-bot, pull requests merged in 2023-09, with the labels that each got.

#300 [TECH] Forcer l'utilisation de node-fetch par Octokit
  common/services/github.js
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#298 [TECH] Ajout d'un job pour configurer automatiquement l'autoscaler d'applications sur Scalingo (PIX-8638)
  common/services/scalingo-client.js
  config.js
  index.js
  run/services/task-scheduler.js
  run/services/tasks.js
  run/services/tasks/autoscale-web.js
  sample.env
  test/integration/run/services/task-scheduler_test.js
  test/integration/run/services/tasks/autoscale-web_test.js
  test/integration/run/services/tasks_test.js
  test/unit/common/services/scalingo-client_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#303 [TECH] Ajout de logs quand l'autoscaler démarre
  run/services/tasks/autoscale-web.js
  test/integration/run/services/tasks/autoscale-web_test.js
Labels: :rocket: Ready to Merge, team-captains, no-review-app

#307 [FEATURE] Ajouter un lien vers la diff lors de la création de la release
  build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
  build/services/slack/view-submissions.js
  common/services/github.js
  test/acceptance/build/slack_test.js
  test/unit/build/services/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#309 [BUGFIX] :bug: Corriger le lien vers le diff dans la vue Slack release-publication-confirmation
  build/services/slack/surfaces/modals/publish-release/release-publication-confirmation.js
  test/acceptance/build/slack_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#311 [TECH] Utiliser un client HTTP pour communiquer avec Slack
  build/controllers/scalingo.js
  build/controllers/slack.js
  common/http-agent.js
  common/services/slack/surfaces/messages/post-message.js
  run/services/slack/commands.js
  run/services/slack/view-submissions.js
  test/integration/build/scalingo_test.js
  test/unit/common/http-agent_test.js
  test/unit/common/services/slack/surfaces/messages/post-message_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK, no-review-app

#310 [FEATURE] :sparkles: Envoyer un message sur slack en cas de changements sur le fichier config.js
  build/services/slack/view-submissions.js
  test/acceptance/build/slack_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#312 [BUGFIX] Corriger le message envoyé sur slack lors de changements du fichier config.js
  build/services/slack/view-submissions.js
  common/services/slack/surfaces/messages/post-message.js
  test/acceptance/build/slack_test.js
  test/unit/common/services/slack/surfaces/messages/post-message_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#315 Empêcher le crash de l'API en cas de configuration incorrecte
  sample.env
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#316 Ne pas tracer durant les tests
  common/services/logger.js
  sample.env
  test/unit/build/services/github_test.js
  test/unit/common/services/logger_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#318 [TECH] Amélioration de la gestion des appels en échec lors de la récupération des derniers tags
  common/services/github.js
  test/acceptance/run/slack_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#313 [TECH] Afficher le label de la team concernée et le lien vers la PR associée au changement de config
  build/services/slack/view-submissions.js
  common/services/github.js
  test/acceptance/build/slack_test.js
  test/unit/build/services/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#322 [TECH] Mettre a jour le chemin de config.js
  common/services/github.js
  test/acceptance/build/slack_test.js
  test/test-helper.js
  test/unit/build/services/github_test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK
