Repository 1024pix/pix-bot, pull requests merged in 2023-02, with the labels that each got.

#215 Mettre à jour les dépendences aussi vite que possible
  .github/renovate.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, blocked

#218 [FEATURE] Déployer pix-lcms-minimal en même temps que la production
  config.js
  run/services/slack/commands.js
  test/unit/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#220 [BUGFIX] Corriger le lien vers PixEditor dans le message automatique envoyée au Reviews Apps
  build/templates/pull-request-messages/pix-editor.md
  test/unit/build/controllers/pull-request-messages/pix-editor.md
Labels: cross-team, :rocket: Ready to Merge

#221 :art: Faire un bump de version mineure par défaut
  run/services/slack/commands.js
  test/unit/run/services/slack/commands_test.js
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK

#223 Corriger la suggestion de déploiement Slack
  run/manifest.js
  test/acceptance/run/manifest_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#214 [BUGFIX] Corrige le nom de l'application Scalingo de review
  build/controllers/github.js
  build/templates/pull-request-messages/pix-data.md
  test/unit/build/controllers/github_test.js
  test/unit/build/controllers/pull-request-messages/pix-bot.md
  test/unit/build/controllers/pull-request-messages/pix-data.md
  test/unit/build/controllers/pull-request-messages/pix-db-replication.md
  test/unit/build/controllers/pull-request-messages/pix-editor.md
  test/unit/build/controllers/pull-request-messages/pix-site.md
  test/unit/build/controllers/pull-request-messages/pix.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#228 :sparkles: Déployer geoapi via Pix bot
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK
