Repository 1024pix/pix-bot, pull requests merged in 2023-05, with the labels that each got.

#246 Ajouter une slash command slack sur les déploiements de DBT
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
  test/acceptance/run/slashcommand_test.js
  test/integration/run/services/slack/commands_test.js
Labels: team-captains, :eyes: Tech Review Needed

#249 Remove mail monitoring
  config.js
  index.js
  package-lock.json
  package.json
  run/services/sendinblue-report.js
  sample.env
  test/unit/run/services/sendinblue-report_test.js
Labels: cross-team, :rocket: Ready to Merge

#250 [TECH] Ajout d'un template de commentaire pour Pix Tutos
  build/templates/pull-request-messages/pix-tutos.md
Labels: :rocket: Ready to Merge

#252 [TECH] Tracer avec le logger dédié partout (PIX-8176)
  .eslintrc.js
  build/controllers/scalingo.js
  build/controllers/slack.js
  build/services/eco-mode-service.js
  build/services/google-sheet.js
  common/pre-response-handler.js
  common/services/cron-job.js
  common/services/github.js
  common/services/logger.js
  common/services/releases.js
  common/services/scalingo-client.js
  common/services/slack/security.js
  common/services/slack/surfaces/messages/post-message.js
  common/services/slack/surfaces/user-infos/get-user-infos.js
  index.js
  run/controllers/slack.js
  run/services/cdn.js
  scripts/get-pull-requests-to-release-in-prod.js
  test/acceptance/build/scalingo_test.js
  test/unit/build/services/github_test.js
  test/unit/common/models/ScalingoAppName_test.js
  test/unit/common/services/logger_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
