Repository 1024pix/pix-bot, pull requests merged in 2024-12, with the labels that each got.

#483 [TECH] Ajouter le déploiement des reviews app de pix-exploit
  build/controllers/github.js
  build/templates/pull-request-messages/pix-exploit.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#477 [FEAT] Ajouter un webhook permettant de bloquer une ip et/ou un ja3 depuis Baleen
  config.js
  run/controllers/security.js
  run/routes/security.js
  run/services/cdn.js
  sample.env
  server.js
  test/acceptance/run/security_test.js
  test/integration/run/services/cdn_test.js
  test/unit/run/controllers/security_test.js
Labels: :rocket: Ready to Merge, team-captains

#447 [FEATURE] Gérer une merge queue
  build/controllers/github.js
  build/controllers/merge.js
  build/controllers/scalingo.js
  build/repositories/pull-request-repository.js
  build/repositories/review-app-repository.js
  build/routes/merge.js
  build/services/merge-queue.js
  common/services/github.js
  config.js
  db/migrations/20241008122744_add-pull-requests-table.js
  sample.env
  test/acceptance/build/github_test.js
  test/integration/build/repositories/pull-request-repository_test.js
  test/integration/build/repositories/review-app-repository_test.js
  test/integration/build/scalingo_test.js
  test/unit/build/controllers/github_test.js
  test/unit/build/controllers/merge_test.js
  test/unit/build/services/github_test.js
  test/unit/run/services/merge-queue_test.js
Labels: cross-team, :rocket: Ready to Merge

#487 [BUGFIX] Utiliser octokit pour trigger le dispatch worfklow event
  build/services/merge-queue.js
  common/services/github.js
  test/unit/build/services/github_test.js
  test/unit/run/services/merge-queue_test.js
Labels: :rocket: Ready to Merge

#486 [TECH] Supprimer l'action auto-merge
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge

#488 [BUGFIX] Ajouter la route merge dans les routes du serveur
  server.js
Labels: :rocket: Ready to Merge

#489 [BUGFIX] Corriger l'injection de dépendance dans le controller merge
  build/controllers/merge.js
  test/acceptance/build/merge_test.js
  test/unit/build/controllers/merge_test.js
Labels: :rocket: Ready to Merge

#490 [FEATURE] Avoir une merge queue par repository
  build/controllers/github.js
  build/controllers/merge.js
  build/repositories/pull-request-repository.js
  build/services/merge-queue.js
  test/acceptance/build/github_test.js
  test/integration/build/repositories/pull-request-repository_test.js
  test/unit/build/controllers/github_test.js
  test/unit/build/controllers/merge_test.js
  test/unit/run/services/merge-queue_test.js
Labels: :rocket: Ready to Merge

#491 [FEATURE] ajoute à la mergequeue lorsque la check_suite se met à jour
  build/controllers/github.js
  common/services/github.js
  test/unit/build/controllers/github_test.js
  test/unit/build/services/github_test.js
Labels: :rocket: Ready to Merge

#493 [BUGFIX] Corriger le payload attendu lors d'un évènement check_suite.
  build/controllers/github.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge

#494 [BUGFIX] Eviter les 500 dans le controller GitHub
  build/controllers/github.js
  test/acceptance/build/github_test.js
Labels: :rocket: Ready to Merge

#495 [BUGFIX] Gérer le cas où la check_suite n'est pas liée à une PR.
  build/controllers/github.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge

#496 [BUGFIX] Ne pas jetter d'erreur quand la PR est déjà dans la merge queue.
  build/repositories/pull-request-repository.js
  test/integration/build/repositories/pull-request-repository_test.js
Labels: :rocket: Ready to Merge

#497 [TECH] Simplifier l'usage de la merge queue
  build/controllers/github.js
  build/controllers/merge.js
  build/services/merge-queue.js
  test/unit/build/controllers/github_test.js
  test/unit/build/controllers/merge_test.js
  test/unit/run/services/merge-queue_test.js
Labels: :rocket: Ready to Merge

#501 [FEATURE] Indiquer dans les PRs qu'elles sont en cours de merge
  build/repositories/pull-request-repository.js
  build/services/merge-queue.js
  common/services/github.js
  test/acceptance/build/github_test.js
  test/integration/build/repositories/pull-request-repository_test.js
  test/unit/build/services/github_test.js
  test/unit/run/services/merge-queue_test.js
Labels: :rocket: Ready to Merge
