Repository 1024pix/pix-bot, pull requests merged in 2024-02, with the labels that each got.

#360 [TECH] Permettre la création de review app sur pix-epreuves.
  build/controllers/github.js
  build/templates/pull-request-messages/pix-epreuves.md
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#361 [BUGFIX] Corrige l'utilisation de `logger.info` lors du déploiement d'un repo.
  common/services/github.js
  common/services/releases.js
  common/services/scalingo-client.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#362 [TECH] Utiliser le logger info à la place du logger ok qui n'existe pas
  common/services/logger.js
  common/services/releases.js
  common/services/scalingo-client.js
  test/unit/common/services/logger_test.js
Labels: :rocket: Ready to Merge, team-captains, no-review-app
