Repository 1024pix/pix-bot, pull requests merged in 2024-11, with the labels that each got.

#462 [TECH] Renommer le endpoint /deploy-pix-data-api-pix
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
  test/acceptance/run/slashcommand_test.js
  test/integration/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge, team-captains

#467 [BUGFIX] Mettre à jour le statut d'une RA quand elle est recréée
  build/repository/review-app-repository.js
  test/integration/build/repository/review-app-repository_test.js
Labels: :rocket: Ready to Merge, team-captains

#471 [FEAT] Permettre la suppression de RA n'ayant pas "-review-pr" dans leur nom
  common/services/scalingo-client.js
  test/unit/common/services/scalingo-client_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#473 [FEATURE] Pix-15117 supprimer les RA lors de l'ajout du label no-review-app
  build/controllers/github.js
  test/acceptance/build/github_test.js
  test/acceptance/scripts/publish_test.js
  test/acceptance/scripts/release-pix-repo_test.js
Labels: :rocket: Ready to Merge
