Repository 1024pix/pix-bot, pull requests merged in 2024-10, with the labels that each got.

#449 [FEATURE] Clôturer les review apps depuis Pix Bot (PIX-14712)
  build/controllers/github.js
  common/services/scalingo-client.js
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
  test/unit/common/services/scalingo-client_test.js
Labels: cross-team, :rocket: Ready to Merge, team-captains

#450 [BUGFIX] Corriger la suppression des RA pour les repo non gérés par Pix Bot (PIX-14712)
  build/controllers/github.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge, team-captains

#455 [TECH] :recycle: Suppression d'un `await` inutile
  build/services/eco-mode-service.js
Labels: :rocket: Ready to Merge, Tech Review OK

#454 [TECH] :package: Ajout d'un client PG
  compose.yaml
  db/PgClient.js
  db/create-database.js
  db/drop-database.js
  db/empty-database.js
  db/knex-database-connection.js
  db/knexfile.js
  db/pg-errors.js
  package-lock.json
  package.json
  sample.env
Labels: :rocket: Ready to Merge, Tech Review OK
