Repository 1024pix/pix-bot, pull requests merged in 2025-07, with the labels that each got.

#586 [FEATURE] releaser la version Jira à la fin du déploiement d'une version en production
  common/services/applications-deployment.service.js
  common/services/jira.service.js
  config.js
  sample.env
  test/integration/common/services/jira.service.test.js
Labels: enhancement, :rocket: Ready to Merge, Tech Review OK

#591 [FEATURE] Déployer pix-exploit depuis pix-bot
  config.js
  run/controllers/slack.js
  run/manifest.js
  run/services/slack/commands.js
  test/acceptance/run/manifest_test.js
Labels: enhancement, :rocket: Ready to Merge, team-captains

#598 [FEATURE] Ignorer les PRs labelisées Hera
  build/controllers/github.js
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge, Tech Review OK, no-review-app

#600 [FEATURE] Permettre de pouvoir tester Pix Bot Integration 🤖
  build/controllers/github.js
  common/services/github.js
  config.js
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
  test/unit/build/services/github_test.js
Labels: :rocket: Ready to Merge, no-review-app

#601 [FEATURE] Créer un message spécifique en cas de création de pull request labelisée Hera (tech-days).
  build/controllers/github.js
  build/templates/pull-request-messages/hera/default.md
  build/templates/pull-request-messages/hera/pix.md
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge, no-review-app

#603 [FEATURE] Gérer l’action synchronize sur les PR Hera
  build/controllers/github.js
  build/repositories/review-app-repository.js
  test/integration/build/repositories/review-app-repository_test.js
  test/unit/build/controllers/github_test.js
Labels: cross-team, :rocket: Ready to Merge, no-review-app

#605 [TECH] Fermeture de PR Hera
  build/controllers/github.js
  test/unit/build/controllers/github_test.js
Labels: cross-team, :rocket: Ready to Merge, no-review-app

#606 [TECH] Supprimer un repo archivé
  build/controllers/github.js
  build/templates/pull-request-messages/pix-api-data-pix.md
Labels: cross-team, :rocket: Ready to Merge, no-review-app

#609 [TECH] Supprimer la colonne `review-apps.isDeployed`
  db/migrations/20250725102927_remove-review-apps-isdeployed.js
Labels: cross-team, :rocket: Ready to Merge, no-review-app

#610 [BUGFIX] Gérer le check-ra-deployment correctement lors d’un synchronize
  build/controllers/github.js
  build/controllers/scalingo.js
  build/repositories/review-app-repository.js
  test/integration/build/repositories/review-app-repository_test.js
  test/unit/build/controllers/github_test.js
Labels: cross-team, :rocket: Ready to Merge, no-review-app

#612 [FEATURE] Gestion du check-ra-deployment sur le label Hera
  build/controllers/github.js
  build/controllers/scalingo.js
  build/repositories/review-app-repository.js
  build/usecases/updateCheckRADeployment.js
  test/acceptance/build/github_test.js
  test/integration/build/repositories/review-app-repository_test.js
  test/integration/build/scalingo_test.js
  test/unit/build/controllers/github_test.js
  test/unit/build/usecases/updateCheckRADeployment_test.js
Labels: cross-team, :rocket: Ready to Merge, no-review-app

#604 [FEATURE] Générer les checkbox de déploiement des RA
  build/controllers/github.js
  build/templates/pull-request-messages/hera/default.md
  build/templates/pull-request-messages/hera/pix-4pix.md
  build/templates/pull-request-messages/hera/pix-api-data-replication.md
  build/templates/pull-request-messages/hera/pix-data.md
  build/templates/pull-request-messages/hera/pix-editor.md
  build/templates/pull-request-messages/hera/pix-epreuves.md
  build/templates/pull-request-messages/hera/pix-exploit.md
  build/templates/pull-request-messages/hera/pix-nina.md
  build/templates/pull-request-messages/hera/pix-site.md
  build/templates/pull-request-messages/hera/pix-tutos.md
  build/templates/pull-request-messages/hera/pix.md
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge, no-review-app

#614 [FEATURE] Générer les liens d’applis et de dashboards dans le commentaire Hera
  build/controllers/github.js
  build/templates/pull-request-messages/hera/default.md
  build/templates/pull-request-messages/hera/pix-4pix.md
  build/templates/pull-request-messages/hera/pix-api-data-replication.md
  build/templates/pull-request-messages/hera/pix-data.md
  build/templates/pull-request-messages/hera/pix-editor.md
  build/templates/pull-request-messages/hera/pix-epreuves.md
  build/templates/pull-request-messages/hera/pix-exploit.md
  build/templates/pull-request-messages/hera/pix-nina.md
  build/templates/pull-request-messages/hera/pix-site.md
  build/templates/pull-request-messages/hera/pix-tutos.md
  build/templates/pull-request-messages/hera/pix.md
  test/unit/build/controllers/github_test.js
Labels: cross-team, no-review-app

#619 [FEATURE] Bye JP, welcome Hera !
  build/controllers/github.js
  build/templates/pull-request-messages/default.md
  build/templates/pull-request-messages/hera/default.md
  build/templates/pull-request-messages/hera/pix-4pix.md
  build/templates/pull-request-messages/hera/pix.md
  build/templates/pull-request-messages/pix-4pix.md
  build/templates/pull-request-messages/pix-api-data-replication.md
  build/templates/pull-request-messages/pix-data.md
  build/templates/pull-request-messages/pix-editor.md
  build/templates/pull-request-messages/pix-epreuves.md
  build/templates/pull-request-messages/pix-exploit.md
  build/templates/pull-request-messages/pix-nina.md
  build/templates/pull-request-messages/pix-site.md
  build/templates/pull-request-messages/pix-tutos.md
  build/templates/pull-request-messages/pix.md
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge, no-review-app

#620 [FEATURE] Supprimer les addons postgres provisionnés sur les fronts (monorepo)
  build/controllers/github.js
  common/services/scalingo-client.js
  test/unit/build/controllers/github_test.js
  test/unit/common/services/scalingo-client_test.js
Labels: cross-team, :rocket: Ready to Merge, Hera

#624 [FEATURE] Éviter de récupérer les infos de la PR quand pas nécessaire
  common/services/github.js
  test/unit/build/services/github_test.js
Labels: cross-team, :rocket: Ready to Merge
