Repository 1024pix/pix-bot, pull requests merged in 2025-08, with the labels that each got.

#630 [BUGFIX] Gérer le cas où la pullRequest est undefined lors d'un event d'édition d'issue comment (TECHDAYS)
  build/controllers/github.js
  test/unit/build/controllers/github_test.js
Labels: cross-team, :rocket: Ready to Merge

#626 [FEATURE] Amélioration du check-ra-deployment
  build/controllers/github.js
  build/controllers/scalingo.js
  build/repositories/review-app-repository.js
  common/services/scalingo-client.js
  test/acceptance/build/github_test.js
  test/integration/build/repositories/review-app-repository_test.js
  test/integration/build/scalingo_test.js
  test/integration/run/services/slack/commands_test.js
  test/unit/build/controllers/github_test.js
  test/unit/common/services/scalingo-client_test.js
Labels: cross-team, :rocket: Ready to Merge

#631 [FEATURE] Ajouter des astuces au message du dépôt pix-data
  build/templates/pull-request-messages/pix-data.md
Labels: :rocket: Ready to Merge

#634 [BUGFIX] Éviter les race conditions d’édition de commentaire
  build/controllers/github.js
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK
