Repository 1024pix/pix-bot, pull requests merged in 2025-02, with the labels that each got.

#516 [FEATURE] Déploiement de maddo à la création/mise à jour des reviews app
  build/controllers/github.js
  build/repositories/review-app-repository.js
  common/services/github.js
  test/acceptance/build/github_test.js
  test/integration/build/repositories/review-app-repository_test.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge

#517 [BUGFIX] Ajouter MaDDo dans le message Github pix-bot
  build/templates/pull-request-messages/pix.md
Labels: cross-team, :rocket: Ready to Merge

#518 [FEATURE] Donner accès aux statistiques rollup sur les RAs pix-epreuves
  build/templates/pull-request-messages/pix-epreuves.md
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#519 [FEATURE] Déployer l’application pix-api-maddo-{environment} (PIX-16552)
  config.js
  test/unit/common/services/releases_test.js
Labels: cross-team, :rocket: Ready to Merge

#520 [BUGFIX] Redeployer la dernière version d'une app comportant un tiret dans son nom
  common/services/releases.js
  config.js
  run/services/slack/commands.js
  test/unit/run/services/slack/commands_test.js
Labels: :rocket: Ready to Merge

#524 [FEATURE] Ajouter maddo dans la liste des apps à déployer en integration.
  config.js
Labels: :rocket: Ready to Merge
