Repository 1024pix/pix-bot, pull requests merged in 2025-05, with the labels that each got.

#554 [BUGFIX] Supprimer du code inutile
  run/services/tasks/release.js
Labels: team-captains, no-review-app

#555 [FEATURE] Permettre au webhook de release de déployer sur osc-fr1
  run/controllers/github.js
  test/unit/run/controllers/github_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK, no-review-app

#563 [FEATURE] Lancer la mise en production automatiquement
  common/services/slack/surfaces/messages/post-message.js
  config.js
  run/services/tasks.js
  run/services/tasks/release-production.js
  sample.env
  test/integration/run/services/tasks_test.js
  test/unit/run/services/tasks/release-production_test.js
Labels: enhancement, :rocket: Ready to Merge, Tech Review OK
