Repository 1024pix/pix-bot, pull requests merged in 2025-06, with the labels that each got.

#570 [BUGFIX] Corriger l'appelle à la fonction d'envoie de message dans la tâche de mise en production
  run/services/tasks/release-production.js
Labels: :rocket: Ready to Merge, Tech Review OK, aggressive

#572 [TECH] Modifier l'application template pour les review apps de pix-db-replication
  build/controllers/github.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#577 [BUGFIX] Utiliser le bon level de log au moment des releases
  common/services/releases.js
Labels: :rocket: Ready to Merge, team-captains

#574 [FEATURE] Notifier via slack lorsque le déploiement des applications est terminé
  common/controllers/index.js
  common/repositories/applications-deployment.repository.js
  common/routes/index.js
  common/services/applications-deployment.service.js
  db/migrations/20250603134355_create-table-applications-deployment.js
  test/acceptance/common/index_test.js
  test/integration/common/repositories/applications-deployment.repository.test.js
  test/integration/common/services/applications-deployment.service.test.js
Labels: enhancement, :rocket: Ready to Merge, Tech Review OK

#579 [BUGFIX] Utiliser le nom complet des applications pour le déploiement
  common/controllers/index.js
  common/repositories/applications-deployment.repository.js
  common/services/applications-deployment.service.js
  test/acceptance/common/index_test.js
  test/integration/common/repositories/applications-deployment.repository.test.js
  test/integration/common/services/applications-deployment.service.test.js
Labels: :rocket: Ready to Merge, Tech Review OK

#581 [BUGFIX] Corriger une typo
  common/services/applications-deployment.service.js
Labels: :rocket: Ready to Merge

#587 [TECH] Commenter le code vérifiant que le build de la version releasée a bien fonctionné avant de MEP
  run/services/tasks/release-production.js
  test/unit/run/services/tasks/release-production_test.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK
