Repository 1024pix/pix-bot, pull requests merged in 2025-03, with the labels that each got.

#529 [TECH] Renommer `pix-data-api-pix` en `pix-api-to-pg`
  build/controllers/github.js
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK

#532 [BUGFIX] Mettre à jour le commit status check-ra-deployment lorsque le label no-review-app est ajouté à la création de la PR.
  build/controllers/github.js
  test/acceptance/build/github_test.js
  test/unit/build/controllers/github_test.js
Labels: :rocket: Ready to Merge, team-captains

#531 [TECH] Ajouter nodemon et une commande pour lancer Pix Bot en mode dev
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge, team-captains, Tech Review OK, no-review-app, dependencies

#527 [FEATURE] Autoriser ou non les mises en production (PIX-16839)
  common/repositories/release-settings.repository.js
  db/migrations/20250305093326_add-release-settings-table.js
  run/services/slack/shortcuts.js
  run/services/slack/surfaces/modals/deploy-release/release-tag-selection.js
  test/acceptance/run/slack_test.js
  test/integration/common/repositories/release-settings.repository.test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#533 [TECH] Ajouter pix-exploit-front-review et renommer pix-exploit-review
  build/controllers/github.js
Labels: :rocket: Ready to Merge, team-captains

#536 [BUGFIX] Ajouter les liens des variables d'environnement pour les pr de pix exploit (PIX-17107)
  build/templates/pull-request-messages/pix-exploit.md
Labels: :rocket: Ready to Merge, team-captains, Tech Review OK, no-review-app

#538 [TECH] Ne pas déployer de pix-exploit-front-review-pr-*
  build/controllers/github.js
Labels: :rocket: Ready to Merge

#539 [REVERT] Revenir à l'ancien template pour Pix exploit
  build/templates/pull-request-messages/pix-exploit.md
Labels: :rocket: Ready to Merge

#540 [FEATURE] pix-epreuves: Lien vers le viewer de composants
  build/templates/pull-request-messages/pix-epreuves.md
Labels: :rocket: Ready to Merge, Tech Review OK

#541 [FEATURE] Ajouter le repo securix
  build/controllers/github.js
Labels: :rocket: Ready to Merge, Tech Review OK

#542 [FEATURE] Utiliser le nouveau nom de domaine du viewer pix-epreuves
  build/templates/pull-request-messages/pix-epreuves.md
Labels: :rocket: Ready to Merge, Tech Review OK
